name: build dockerfile and run

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    - name: docker build
      env:
        SECRET: {{ secrets.SUPERSECRET }}
      run: |
           docker build --tag test:v.0.1 .

    - name: docker run
      run: docker run test:v.0.1
